# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub Statistics

on:
  push:
    branches: [ main ]
  schedule:
  - cron: '30 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Compile statistics
      run: |
        java --version
        java -cp target/gs-1.0-jar-with-dependencies.jar Main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
    - name: Commit new outputs
      run: |
        git config --global user.name 'github-statistics'
        git config --global user.email 'github-statistics@tanjeffreyz.github.io'
        git add * || true
        git commit -m 'Updated statistics' || true
        git push
